angular.module('userModule')
.controller('activitiesController',function($scope,OperationsActivities,$location){
	console.log("entro");
	$scope.activity={
		idActividad:"",
		nombre:"",
		descripcion:"",
		fecha:"",
		cupo:"",
		lugar:"",
		horaInicio:"",
		horaFinal:"",
		duracion:""
	};
	$scope.getlistaActivities =OperationsActivities.getActivity(function(res){
		console.log(res);
		$scope.listaActivities=res;
		console.log($scope.listaActivities);
	});
	$scope.postActivities=function(activity){
		console.log(activity);
		OperationsActivities.insertActivity($scope.activity,function(res){
			if(res){
				OperationsActivities.getActivity(function(res){
					console.log(res);
					$scope.listaActivities=res;
					console.log($scope.listaActivities);
					window.location.href="#/users/activities";
				});
			}
		});
	}
	$scope.delete=function deleteActivity(id){
		console.log("imprime:"+$scope.activity.idActividad);
		OperationsContacts.deleteActivities($scope.contacto.idActividad,function(response){
				if(response.success){
				    $location.path('contactos');
				    $route.reload();
				}
		});

	};
});
